# Generated by Django 4.1.7 on 2023-03-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_alter_project_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="owner",
            new_name="project_manager",
        ),
        migrations.AddField(
            model_name="project",
            name="priority",
            field=models.CharField(
                choices=[
                    ("Low", "Low"),
                    ("Medium", "Medium"),
                    ("High", "High"),
                ],
                default="Medium",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("Not Started", "Not Started"),
                    ("In Progress", "In Progress"),
                    ("On Hold", "On Hold"),
                ],
                default="Not Started",
                max_length=50,
            ),
        ),
    ]
