# Generated by Django 4.1.7 on 2023-03-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_alter_task_due_date_alter_task_is_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
